#include <iostream>

using namespace std;

int main() {
    int nilai_awal, nilai_akhir;

// Meminta input dari user
    cout << "Masukan nilai awal";
    cin >> nilai_awal;
    cout << "Masukan nilai akhir";
    cin >> nilai_akhir;

    // Perulangan nilai awal - nilai akhir

    for(int i = nilai_awal; i <= nilai_akhir; i++)  {
        cout << i << "Classyscience.iu" << endl;

    }
    return 0;

}